apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-sleeper
  template:
    metadata:
      labels:
        app: ubuntu-sleeper
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        command: ["sleep", "infinity"]