apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 1h
  url: oci://public.ecr.aws/karpenter
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: kube-system
spec:
  interval: 2m
  chart:
    spec:
      chart: karpenter
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  install:
    createNamespace: false
  values:
    settings:
      clusterName: platform
      interruptionQueue: Karpenter-platform
    controller:
      # Lower resources than normal because the node pools we created use small EC2s.
      resources:
        requests:
          cpu: "300m"
          memory: "300Mi"
        # limits:
        #   cpu: 1
        #   memory: 1Gi
---
# https://karpenter.sh/docs/concepts/nodeclasses/
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: Karpenter-platform-2024121315250968540000001a
  amiFamily: AL2023
  amiSelectorTerms:
    - tags:
        karpenter.sh/discovery: platform
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: platform
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: platform
  tags:
    KarpenterManaged: "true"
    Terraform: "true"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: 
            - "t4g.medium"
            - "c6g.medium"
            - "m6g.medium"
  limits:
    cpu: 100
    memory: 100Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s