apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
  labels:
    kubernetes.io/metadata.name: karpenter
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 1h
  url: oci://public.ecr.aws/karpenter
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 2m
  chart:
    spec:
      chart: karpenter
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  install:
    createNamespace: false
  values:
    settings:
      clusterName: platform
      interruptionQueue: Karpenter-platform
    controller:
      # Lower resources than normal because the node pools we created use small EC2s.
      resources:
        requests:
          cpu: "300m"
          memory: "300Mi"
        # limits:
        #   cpu: 1
        #   memory: 1Gi