---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: infra-configs # defined in infra.yaml in this dir.
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kube/apps/platform
  prune: true
  wait: true
  timeout: 5m0s